version: '3.9'

services:
  database:
    image: postgres
    container_name: twilio-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=twilio_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
    volumes:
       - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: twilio
    restart: always
    ports:
      - 3030:3030
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local